import argparse
import os


class ContextOptimizer:
    def __init__(self, *, rules_dir: str):
        self.rules_dir = rules_dir

    def optimize_context(self, *, workspace_dir: str) -> None:
        if not os.path.exists(workspace_dir):
            print(f"Error: Workspace '{workspace_dir}' does not exist.")
            return

        # Stack markers detection
        is_python = False
        is_frontend = False
        is_obsidian = ".obsidian" in workspace_dir or "vault" in workspace_dir

        for root, _, files in os.walk(workspace_dir):
            # Skip build/dependency folders
            if any(x in root for x in ['node_modules', 'dist', '.next', 'out', '.venv', '.git']):
                continue

            for file in files:
                if file in ['requirements.txt', 'pyproject.toml', 'setup.py', 'Pipfile'] or file.endswith('.py'):
                    is_python = True
                if file in ['package.json', 'tsconfig.json', 'next.config.js', 'vite.config.ts'] or file.endswith(('.ts', '.tsx', '.js', '.jsx')):
                    is_frontend = True
                if file == '.obsidian' or root.endswith('.obsidian'):
                    is_obsidian = True

        # Collecting active rule sets based on profile
        profile = os.environ.get("AGY_RULES_PROFILE", "strict").lower()
        active_stacks = []
        rule_files = ["common.md"]

        if profile == "minimal":
            active_stacks.append("Minimal Profile (Common rules only)")
        else:
            if is_python:
                rule_files.append("python.md")
                active_stacks.append("Python")
            if is_frontend:
                rule_files.append("frontend.md")
                active_stacks.append("Frontend")
            if is_obsidian:
                rule_files.append("obsidian.md")
                active_stacks.append("Obsidian")

        if not active_stacks:
            active_stacks.append("None (Common only)")

        # Compile AGENTS.md
        compiled_rules = [
            f"# [AUTO-GENERATED] Selective Agent Rules (Active Stacks: {', '.join(active_stacks)})",
            "\n<!-- WARNING: Do not edit this file directly. It is auto-generated by context_optimizer.py -->\n"
        ]

        for rule_file in rule_files:
            file_path = os.path.join(self.rules_dir, rule_file)
            if os.path.exists(file_path):
                try:
                    with open(file_path, encoding='utf-8') as f:
                        compiled_rules.append(f.read())
                    compiled_rules.append("\n---\n")
                except Exception as e:
                    print(f"Failed to read rule file {rule_file}: {e}")

        # Читаем локальные правила разработчика (AGENTS.local.md)
        local_rules_path = os.path.join(workspace_dir, "AGENTS.local.md")
        if os.path.exists(local_rules_path):
            try:
                with open(local_rules_path, encoding="utf-8") as f:
                    local_rules_content = f.read()
                compiled_rules.append(
                    f"\n## 👤 Локальные правила разработчика (AGENTS.local.md)\n{local_rules_content}"
                )

                # Авто-добавление в .gitignore
                gitignore_path = os.path.join(workspace_dir, ".gitignore")
                if os.path.exists(gitignore_path):
                    with open(gitignore_path, encoding="utf-8") as f:
                        git_content = f.read()
                    if "AGENTS.local.md" not in git_content:
                        newline = "" if git_content.endswith("\n") else "\n"
                        with open(gitignore_path, "a", encoding="utf-8") as f:
                            f.write(f"{newline}# Local developer rules\nAGENTS.local.md\n")
            except Exception as e:
                print(f"Failed to read local rules or update .gitignore: {e}")

        # Ensure .agents folder exists in workspace
        agents_dir = os.path.join(workspace_dir, ".agents")
        os.makedirs(agents_dir, exist_ok=True)

        agents_file_path = os.path.join(agents_dir, "AGENTS.md")
        try:
            with open(agents_file_path, 'w', encoding='utf-8') as f:
                f.write("\n".join(compiled_rules))
            print(f"✅ Generated selective rules at: {agents_file_path}")
        except Exception as e:
            print(f"Failed to write AGENTS.md: {e}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Optimize and compile agent rules based on workspace stack.")
    parser.add_argument("workspace", help="Path to the workspace to scan.")
    args = parser.parse_args()

    try:
        from tools import config
    except ImportError:
        import config
    default_rules_dir = os.path.join(config.get_workspace_root(), "vault", "reference", "rules")
    optimizer = ContextOptimizer(rules_dir=default_rules_dir)
    optimizer.optimize_context(workspace_dir=args.workspace)
